version: '3'
services:
  app-nginx:
    env_file: ./.env
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - ${NGINX_PORT}:80
      - ${APP_NGINX}:81
      - '443:443'
    environment:
      DB_MYSQL_HOST: ${DB_MYSQL_HOST}
      DB_MYSQL_PORT: ${DB_MYSQL_PORT}
      DB_MYSQL_USER: ${DB_MYSQL_USER}
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${DB_MYSQL_NAME}
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  db-nginx:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_PORT: ${DB_MYSQL_PORT}
    volumes:
      - ./data/mysql:/var/lib/mysql


