version: '3.7'

services:

  portainer:
    env_file: ./.env
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: --admin-password-file '/data portainer/ portainer/portainer-ce/senha-portainer'
    ports: 
      - ${PORTAINER_SERVER_PORT}:8000
      - ${PORTAINER_HTTP_PORT}:9000
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_HOME}:/data portainer/ portainer/portainer-ce
    networks:
      - server

  jenkins:
    image: axltxl/jenkins-dood
    env_file: ./.env
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${JENKINS_HTTP_PORT}:8080
    networks:
      - server

networks:
  server:
